version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serviceMonitoring-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2jelntusxn9m"
s3_prefix = "serviceMonitoring-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

