export const SERVICETYPES : any = ['TV Installation','AC Installation','Fan Installation','WM Installation','Dish Installation'];
export const CITYVIEW : any = 
{
    "entityList":
    [
        {
            "entityName":"Delhi",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":23,
                    "availableCapacity":14
                },
                {
                    "totalCapacity":13,
                    "availableCapacity":4
                },
                {
                    "totalCapacity":18,
                    "availableCapacity":2
                },
                {
                    "totalCapacity":50,
                    "availableCapacity":43
                },
                {
                    "totalCapacity":77,
                    "availableCapacity":65
                },
                {
                    "totalCapacity":53,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":29,
                    "availableCapacity":25
                }
            ]
        },
        {
            "entityName":"Jaipur",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":48,
                    "availableCapacity":34
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":97,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":45,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":59,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":34,
                    "availableCapacity":15
                },
                {
                    "totalCapacity":14,
                    "availableCapacity":3
                }
            ]
        },
        {
            "entityName":"Mumbai",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":32,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":17,
                    "availableCapacity":1
                },
                {
                    "totalCapacity":87,
                    "availableCapacity":0
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":4
                },
                {
                    "totalCapacity":65,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":74,
                    "availableCapacity":24
                },
                {
                    "totalCapacity":12,
                    "availableCapacity":0
                }
            ]
        },
        {
            "entityName":"Kolkata",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":48,
                    "availableCapacity":34
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":97,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":45,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":59,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":34,
                    "availableCapacity":15
                },
                {
                    "totalCapacity":14,
                    "availableCapacity":3
                }
            ]
        },
        {
            "entityName":"Ahmedabad",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":48,
                    "availableCapacity":34
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":97,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":45,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":59,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":34,
                    "availableCapacity":15
                },
                {
                    "totalCapacity":14,
                    "availableCapacity":3
                }
            ]
        },
        {
            "entityName":"Hyderabad",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":48,
                    "availableCapacity":34
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":97,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":45,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":59,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":34,
                    "availableCapacity":15
                },
                {
                    "totalCapacity":14,
                    "availableCapacity":3
                }
            ]
        },
        {
            "entityName":"Bangalore",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":48,
                    "availableCapacity":34
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":97,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":45,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":59,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":34,
                    "availableCapacity":15
                },
                {
                    "totalCapacity":14,
                    "availableCapacity":3
                }
            ]
        }
    ]
};

export const MERCHANTVIEW : any =
{
    "entityList":
    [
        {
            "entityName":"Dinakar",
            "merchantId":"MI1234",
            "capacityList":
            [
                {
                    "totalCapacity":23,
                    "availableCapacity":14
                },
                {
                    "totalCapacity":13,
                    "availableCapacity":4
                },
                {
                    "totalCapacity":18,
                    "availableCapacity":2
                },
                {
                    "totalCapacity":50,
                    "availableCapacity":43
                },
                {
                    "totalCapacity":77,
                    "availableCapacity":65
                },
                {
                    "totalCapacity":53,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":29,
                    "availableCapacity":25
                }
            ]
        },
        {
            "entityName":"Gupta",
            "merchantId":"MI8723",
            "capacityList":
            [
                {
                    "totalCapacity":48,
                    "availableCapacity":34
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":97,
                    "availableCapacity":21
                },
                {
                    "totalCapacity":45,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":59,
                    "availableCapacity":32
                },
                {
                    "totalCapacity":34,
                    "availableCapacity":15
                },
                {
                    "totalCapacity":14,
                    "availableCapacity":3
                }
            ]
        },
        {
            "entityName":"Sharma",
            "merchantId":"",
            "capacityList":
            [
                {
                    "totalCapacity":32,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":17,
                    "availableCapacity":1
                },
                {
                    "totalCapacity":87,
                    "availableCapacity":0
                },
                {
                    "totalCapacity":42,
                    "availableCapacity":4
                },
                {
                    "totalCapacity":65,
                    "availableCapacity":12
                },
                {
                    "totalCapacity":74,
                    "availableCapacity":24
                },
                {
                    "totalCapacity":12,
                    "availableCapacity":0
                }
            ]
        }
    ]
};