AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

Globals:
  Function:
    Timeout: 20

Resources:
  ServiceCapacityTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceCapacityTrackerFunction
      Handler: com.amazon.vas.ServiceCapacityTracker.Activity.ServiceCapacityTrackerActivity::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE